services:
  go-db:
    container_name: psql_db
    image: postgres:latest
    volumes:
      - psql_volume:/var/lib/postgresql/data
    env_file:
      - path: psql-env/.env
        required: true
    ports:
      - 2345:5432
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "100M"
        reservations:
          cpus: "0.50"
          memory: "50M"
    

volumes:
  psql_volume:
